import Head from 'next/head';

import Header from '../components/Header';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';

export default function Home() {
  return (
    <div className="w-full h-full justify-center items-center">
      <Head>
        <title>Ulvi Suleymanov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url(&apos;https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;900&display=swap&apos;);
        </style>
      </Head>
      <Header />
      <Main />
      <Skills />
      <Projects />
    </div>
  );
}
